### ISSUE TITLE
ServeTypeScript import statement only imports a single file

### ISSUE THREAD

**Issue by Jictyvoo** [drashland/deno-drash-middleware#88]
## Summary

When using ServeTypeScript to import multiple typescript files, the generated file (in-memory), contains only one typescript file, and the original file content selected in config doesn't appear in the memory. Example, if you have 4 files: `main.ts`, `a.ts`, `b.ts`, `c.ts`, and `main.ts` import all 3 files, only one of them will appear in browser, and the `main.ts` content is missing in the memory file.

## Steps To Reproduce The Bug

1. Write the config choosing the realPathSync of `main.ts` file
```typescript
import { ServeTypeScript } from "../deps.ts";
const serveCompiledTs = ServeTypeScript({
  files: [
    {
      source: Deno.realPathSync("./frontsystem/main.ts"), // the path to the actual TypeScript file
      target: "/ts/frontsystem.min.ts", 
    },
  ],
});
```
2. Write main.ts to import 4 other files
```typescript
//main.ts
import { A } from "./models/A.ts";
import { B } from "./util/B.ts";
import { C } from "./views/C.ts";
import { D } from "./views/D.ts";
const B = new B();
console.log("I'm working");
//models/A.ts
class A {
    public name: string;
    constructor(){
        this.name = 'name';
    }
}
//same to other files
```
3. Run the server.
4. Verify the file at the browser.

## Expected Behavior

All files imported together

## Suggested Solution(s)

Still learning, sorry

## Additional Context

Files used in the original problem has more than 300 lines each

**Comment by ebebbington** [comment]
I believe this is because `Deno.compile` isn't converting the `export lines`. @Jictyvoo the resulting file only shows the contents of one file because the compiled file has errors when it's compiled, whcih are:

1. `const B = new B()` will not work (same goes for other files, external issue), and must be changed to `const b = new B()`.
2. `Deno.compile` isn't converting `export` syntax (external/internal issue)

Currently checking if `Deno.compile` is acting as it should

i think this highlights that we should throw errors in more cases, such as these so it doesn't 'look like' everything went ok when the server is ran, when in reality, it didn't

FYI The errors seen are from viewing the console in the browser - You can see the compild result by running `Deno.compile` in the `deno` repl

**Comment by ebebbington** [comment]
UPDATE: Seems both `Deno.compile` and `Deno.transpileOnly` won't strip exports, essentially not making them browser compatible - @crookse i think we might have to go with https://doc.deno.land/builtin/unstable#Deno.bundle

**Comment by ebebbington** [comment]
@Jictyvoo for the time being, you might have to use `deno bundle` to **manually** transpile the files

**Comment by Jictyvoo** [comment]
@ebebbington thanks for the support.
On my example `const B = new B()` was incorrect, is `b` sorry for the error. 
Will you update the middleware to use `Deno.bundle`?

**Comment by ebebbington** [comment]
@Jictyvoo it would need to be discussed first, but I *personally* think we’ll end up going with it as it seems to be the only solution

**Comment by crookse** [comment]
@Jictyvoo , this will be released in the next 24 hours. stay tuned!
